### PR TITLE
(Reopen) Made URP Shader compatible with Forward+ renderer.

### PR DESCRIPTION
**Pull request by mseonKim**
(Reopened pull request since some unnecessary custom codes were included.)

Added a keyword and new GlobalIlluminationUTS function to support Forward+ (Marked the original function as deprecated arbitrarily, please remove or rename it as you wish.)

And I added UTS_LIGHT_LOOP_BEGIN macro for additional lights as well, with a quite long code to support additional directional lights without modularization in case it would violate the code convention...

### CODE REVIEW

**Comment by H3idi-X** [comment]
Thanks you very much. I started to check forward plus and your PR today.

**Comment by H3idi-X** [comment]
Hi, I changed your PR target branch to another branch I created to test your PR and merged to it.

**Comment by H3idi-X** [comment]
You don't need to close this PR at this moment. because we might have to talk a bit. Thank you very much!

**Comment by H3idi-X** [comment]
Oh, sorry, I didn't notice that the PR is closed when I merged to other branch. you can continue to talk in this PR thread.

**Comment by H3idi-X** [comment]
Hi, I checked the PR and found the following scenes in the URP samples are not rendered correctly.

- ToonSader_Fierfly:
- SceneLights Hi-Cut_Filter Test
- PointLightTest
- NormalMap
- Will you please check above in the bracnh task/fowardPlus_TestPR

Thanks.

**Comment by mseonKim** [comment]
Hi, thanks for taking the time to test my PR, I will test those and get back to you soon!

**Comment by mseonKim** [comment]
Hi, I was able to find the difference in the scenes above. Initially, I suspected that Forward+ clustering was the cause, but it turns out that an additional light step offset (_StepOffset) was the cause. If this value is set to 0, the rendering will appear identical to normal forward rendering. I will continue to investigate this and give you an update as soon as possible.

**Comment by mseonKim** [comment]
Hi, I opened another pull request :) please check out the new PR at your convenience!

**Pull request merged**
