### PR TITLE
Fixed a bug where plain could not be selected

### PR DESCRIPTION
**Pull request by Hum9183**
# Summary
- The following issues have been fixed.
- https://github.com/Unity-Technologies/com.unity.toonshader/issues/238
- https://github.com/Unity-Technologies/com.unity.toonshader/issues/358

# Environment
- OS: Windows11
- Unity Versions: 
    - [x] 2023.2.17f1 URP Forward
    - [x] 2022.3.5f1   URP Forward
    - [x] 2022.3.5f1   URP Forward+
    - [x] 2022.3.5f1   BRP
    - [x] 2021.3.37f1 URP Forward
    - [x] 2020.3.48f1 URP Forward

# Details
- The bug seems to be caused by the fact that OutlinePass is written before ForwardLitPass.
- I was able to fix this by putting the description of OutlinePass after ForwardLitPass.
- I don't think this fix will cause the Outline to be drawn incorrectly.
- The bug did not occur in HDRP

### CODE REVIEW

**Comment by H3idi-X** [comment]
Thank you, as always, for your contribution. We will review your PR sometime next month, as we currently have higher priority tasks to address.

**Comment by H3idi-X** [comment]
Thank you for your commitment.

I have created a PR target branch for our internal testing and attempted to merge this PR into it. However, we are currently encountering some conflicts. Could you please resolve these conflicts on your end?

Thank you!

**Comment by H3idi-X** [comment]
We mereged manually.

**Comment by Hum9183** [comment]
@H3idi-X 
Hi, I've been a little busy and didn't notice.
I will try to fix the conflicts when I have more time.

**Comment by Hum9183** [comment]
@H3idi-X
 > We mereged manually.

I didn't read it properly.
Thanks for manually merging.
If you have any questions, feel free to ask.

**Comment by H3idi-X** [comment]
Thank you as always!
We mereged the test branch to evaluate your PR to our Main Branch. We might have to do some chores. But, the fix will be included in the next release.

**Pull request closed without merging**
